//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrueFriends
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advert
    {
        public int Advert_ID { get; set; }
        public string Advert_Name { get; set; }
        public int Advert_AnimalAge { get; set; }
        public decimal Advert_AnimalWeight { get; set; }
        public string Advert_KindOfAnimal { get; set; }
        public string Advert_Description { get; set; }
        public string Advert_Image { get; set; }
        public Nullable<int> Advert_Creator { get; set; }
        public Nullable<System.DateTime> Advert_CreationDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
