//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrueFriends
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Comment_ID { get; set; }
        public string Comment_Text { get; set; }
        public Nullable<int> Comment_Creator { get; set; }
        public Nullable<System.DateTime> Comment_CreationDate { get; set; }
    
        public virtual User User { get; set; }
    }
}
